### ISSUE TITLE
What motivation to do this work?

### ISSUE THREAD

**Issue by deviator** [carblue/tasn1#1]
Why you are not using [ans1-d](https://github.com/JonathanWilbur/asn1-d) package?

**Comment by carblue** [comment]
Hi,
ans1-d package is unable to work with ASN.1 module files *.asn (or did I miss something?).
Supposed You have these bytes (hex. representation)
61 1F 4F 10 41 43 4F 53 50 4B 43 53 2D 31 35 76 31 2E 30 30 50 05 65 43 65 72 74 51 04 3F 00 41 00
and You expect (or want to check that) it is an encoding for "DIRRecord" (in PKCS15.asn), then I want to be able to do this check and in the success case print something like this (decoded content):
```
name: dirRecord  type: SEQUENCE
  name: aid  type: OCT_STR  value: 41434f53504b43532d313576312e3030 "ACOSPKCS-15v1.00"
  name: label  type: UTF8_STR  value: eCert
  name: path  type: OCT_STR  value: 3f004100
```
Given, that GNU libtasn1 is out there for some years (IMO well accepted and solves my needs), I wonder why JonathanWilbur spends 1000+ hours on doing a lot from scratch in D, but it takes me only about 2-3h for a libtasn1 D binding.

**Comment by deviator** [comment]
Thanks for explain!

**Comment by carblue** [comment]
With software, that can't make use of e.g. PKCS15.asn (like asn1-d package or https://lapo.it/asn1js), You'll get so far and no further (and must do everything else in Your source code):
```
Application 1 (3 elem)
  Application 15 ACOSPKCS-15v1.00
  Application 16 eCert
  Application 17 (4 byte) 3F004100
```
See the unittest beginning in line 644 of https://github.com/carblue/tasn1/blob/master/wrapper/wrapper/libtasn1.d how "easy" it is to make use of the PKCS15.asn information with libtasn1: E.g. all You need for the test/assert "It is DIRRecord !" are lines 571+596+648+650+653.
And with function asn1_print_structure out-of-the-box You get a print result similar to what is shown in my first comment (actually I used a scanning function that does a little bit more "pretty-print").
